.PHONY: sync
sync: lib/install.sh lib/library_scripts.sh
	@for d in src/*/; do cp -a $^ "$$d" >/dev/null 2>&1; done

feature?=*
.PHONY: test
test: $(wildcard test/$(feature)/scenarios.json)
	@devcontainer features test -f $(patsubst test/%/scenarios.json,%,$^) --skip-autogenerated

test_cmdline?=""
.PHONY: gen-test
gen-test:
	 @scripts/gen_test.sh $(feature) '$(test_cmdline)'
