name: "CI - Test Features"
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:

  data-scenarios:
    runs-on: ubuntu-latest
    outputs:
      scenarios: ${{ steps.data.outputs.scenarios }}
    steps:
      - uses: actions/checkout@v4
      - id: data
        run: |
          echo ${{ steps.changes.outputs.changes }}
          echo "scenarios=$(make ci-features-pathspecs)" >> $GITHUB_OUTPUT

  changed-only:
    runs-on: ubuntu-latest
    needs:
      - data-scenarios
    outputs:
      scenarios: ${{ steps.data.outputs.changes }}
    steps:
      - uses: dorny/paths-filter@v3
        id: data
        with:
          filters: ${{ fromJson(needs.data-scenarios.outputs.scenarios) }}

  test-scenarios:
    needs: 
      - changed-only
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ needs.changed-only.outputs.scenarios }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Docker login ghcr"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: "Test features scenarios"
        run: make feature=${{ matrix.features }} test


