name: "CI - Test Features"
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  data-scenarios:
    runs-on: ubuntu-latest
    outputs:
      scenarios: ${{ steps.data.outputs.scenarios }}
    steps:
      - uses: actions/checkout@v4
      - id: data
        run: |
          echo "scenarios=$(make ci-test-targets)" >> $GITHUB_OUTPUT
  filter-changes:
    needs:
      - data-scenarios
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.data-scenarios.outputs.scenarios) }}
    permissions:
      pull-requests: read
    outputs:
      feature-paths: ${{ steps.filter.outputs.feature_paths }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            feature_paths:
              - 'src/${{ matrix.features }}/**'
              - 'test/${{ matrix.features }}/**'

  test-scenarios:
    needs: 
      - data-scenarios
      - filter-changes
    if: ${{ needs.filter-changes.outputs.feature-paths == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.data-scenarios.outputs.scenarios) }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Docker login ghcr"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: "Test features scenarios"
        run: make feature=${{ matrix.features }} test


