name: "CI - Test Features"
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  data-scenarios:
    runs-on: ubuntu-latest
    outputs:
      scenarios: ${{ steps.data.outputs.scenarios }}
    steps:
      - uses: actions/checkout@v3
      - id: data
        run: |
          echo "scenarios=$(make ci-test-targets)" >> $GITHUB_OUTPUT

  test-scenarios:
    needs: data-scenarios
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.data-scenarios.outputs.scenarios) }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Docker login ghcr"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: "Test features scenarios"
        run: make feature=${{ matrix.features }} test


