name: "Validate devcontainer-feature.json files"
on:
  workflow_dispatch:
  pull_request:

jobs:
  data-features:
    runs-on: ubuntu-latest
    outputs:
      features: ${{ steps.data.outputs.features }}
    steps:
      - uses: actions/checkout@v4
      - id: data
        run: |
          echo "features=$(make ci-features-paths)" >> $GITHUB_OUTPUT
  validate:
    needs: data-features
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.data-features.outputs.features) }}
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ matrix.features }}

      - name: "Validate devcontainer-feature.json files"
        uses: devcontainers/action@v1
        with:
          validate-only: "true"
          base-path-to-features: "./src"
