name: "Validate devcontainer-feature.json files"
on:
  workflow_dispatch:
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      features: ${{ steps.data.outputs.features }}
    steps:
      - uses: actions/checkout@v4
      - id: data
        run: |
          echo "features=$(make ci-features-paths)" >> $GITHUB_OUTPUT
  validate:
    needs: 
      - setup
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.features) }}
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ matrix.features }}
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            changed:
              - '${{ matrix.features }}/devcontainer-feature.json'

      - name: "Validate devcontainer-feature.json files"
        uses: devcontainers/action@v1
        if: steps.filter.outputs.changed == 'true'
        with:
          validate-only: "true"
          base-path-to-features: "./src"
